name: alvsell
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gadzety/Magnes wejście.png
    - assets/gadzety/Magnes kopuły pionowy.png
    - assets/gadzety/Magnes kopuły poziomy.png
    - assets/gadzety/Długopis.png
    - assets/gadzety/Butelka Czarna.png
    - assets/gadzety/Butelka pomarańczowa.png
    - assets/gadzety/Smycz.png
    - assets/gadzety/Zdjęcie.png
    - assets/gadzety/Kawa.png
    - assets/TłoAlvSell.png

    - assets/fonts/arial/ARIAL.TTF

